name: Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  save_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python packages
        run:  |
          pip install matplotlib requests
      
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
      
      # "cloudflare is my number one opp" -willemsteller
      - name: Clone & run flare-bypasser
        run: |
          git clone https://github.com/yoori/flare-bypasser
          cd flare-bypasser
          docker-compose up -d
          sleep 20 # oh nawwwwwww
          cd ..
      
      - name: Get data
        run: python getjson_cfbypass.py

      - name: Visualise and save data
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "Update"
          git push
