name: Image

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *' # This will trigger the workflow every day at midnight UTC

jobs:
  save_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python packages
        run:  |
          pip install matplotlib requests
      
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
      
      # "cloudflare is my number one opp" -willemsteller
      - name: Clone & run flare-bypasser
        run: |
          git clone https://github.com/yoori/flare-bypasser
          cd flare-bypasser
          docker-compose up -d

          MAX_RETRIES=10
          RETRY_INTERVAL=10
          
          for i in $(seq 1 $MAX_RETRIES); do
            nc -zv localhost 20080 && echo "Port 20080 is open!" && break
            echo "Waiting for port 8080 to be open... ($i/$MAX_RETRIES)"
            sleep $RETRY_INTERVAL
          done
          
          if ! nc -zv localhost 20080; then
            echo "Port 20080 is not open after $MAX_RETRIES attempts."
            exit 1
          fi
          cd ..
      
      - name: Get data
        run: python getjson_cfbypass.py

      - name: Visualise and save data
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "Update"
          git push
