name: Image

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *' # This will trigger the workflow every day at midnight UTC

jobs:
  save_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt install -y openvpn dialog python3-pip python3-setuptools

      - name: Install packages
        run: pip install matplotlib requests protonvpn-cli

      - name: Run ProtonVPN
        env:
          PROTONVPN_USERNAME: ${{ secrets.PROTONVPN_USERNAME }}
          PROTONVPN_PASSWORD: ${{ secrets.PROTONVPN_PASSWORD }}
        run: |
          echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}\n3\nudp\ny" | protonvpn init
          protonvpn c -f &

      - name: Get data
        run: python getjson.py

      - name: Disconnect from ProtonVPN
        run: protonvpn d

      - name: Visualise and save data
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "Update"
          git push
