name: Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  save_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python packages
        run:  |
          pip install matplotlib requests numpy
      
      # "cloudflare is my number one opp" -willemsteller
      - name: Run flare-bypasser
        run: |
          docker run -d -p 20080:8080 --pull always ghcr.io/yoori/flare-bypasser:latest
          sleep 15 # i didnt had any better ideas, forgive me
      
      - name: Get data
        run: python getjson_cfbypass.py

      - name: Visualise and save data
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'noreply@github.com'
          git add .
          git commit -m "Update"
          git push
